# -*- coding: utf-8 -*-
"""Estatística- Probabilidade e Amostragem Desafio Final WMC 16-09-2024 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQzvtK8OB9wh-BlOkn3SMeQbb_aQq46v

### Desafio - Probalidade e Amostragem
### Aluna: Isabela de Souza Silva
### Squad: Grace Hopper
"""

# Primeiro passo, importação das bibliotecas que poderei precisar

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math

#Leitura do nosso dataframe:

data = pd.read_csv('/content/populacao_brasileira.csv.csv')

# Fazendo uma pequena visualização:  :)

data.head(10)

# 1. Considere pessoas fluentes em inglês, qual a probabilidade complementar?
# Ou seja, qual a probabilidade de escolhermos uma pessoa aleatória e ela não ser fluente em inglês. Considere fluente quem tem o nível avançado.

total_pessoas = len(data)
fluentes = len(data[data['nível de proficiência em inglês'] == 'Avançado'])
prob_nao_fluente = (total_pessoas - fluentes) / total_pessoas

print(f"Probabilidade de não ser fluente: {prob_nao_fluente:.2%}")

# 2. Se uma pessoa escolhida aleatoriamente for de Alagoas ou do Pará,
# qual é a probabilidade de ela ter uma renda superior a 5 mil reais?


# Precisamos fazer os passos:

#Filtrando as pessoas de AL ou PA
al_pa = data[data['estado'].isin(['AL', 'PA'])]

# Contando o total de pessoas de AL ou PA
total_al_pa = len(al_pa)

# Filtrando pessoas com renda superior a 5 mil reais
renda_superior_5k = al_pa[al_pa['renda'] > 5000]

# Contando o número de pessoas com renda superior a 5 mil
total_renda_superior_5k = len(renda_superior_5k)

# Calculando a probabilidade
prob_renda_superior_5k = total_renda_superior_5k / total_al_pa if total_al_pa > 0 else 0

print(f"Probabilidade de uma pessoa de AL ou PA ter renda superior a 5 mil: {prob_renda_superior_5k:.2%}")

# 3. Descubra a probabilidade de uma pessoa ter ensino superior completo no estado do Amazonas.
#  Qual a probabilidade da quinta pessoa que você conversar, que é amazonense, ter ensino superior completo?


# Primeiro é preicso filtrar dados para o estado do Amazonas
df_amazonas = data[data['estado'] == 'AM']

# Segundo passo é calcular a probabilidade de ter ensino superior completo no Amazonas
probabilidade_superior = (df_amazonas['escolaridade'] == 'Superior').mean()
print(f'Probabilidade de uma pessoa ter ensino superior completo no Amazonas: {probabilidade_superior:.2f}')

# Terceiro passo é verificar se a quinta pessoa (índice 4) do estado do Amazonas tem ensino superior completo ou não
quinta_pessoa_superior = df_amazonas.iloc[4]['escolaridade'] == 'Superior'
print(f'A quinta pessoa tem ensino superior completo? {"Sim" if quinta_pessoa_superior else "Não"}')

# 4. Considerando a renda das pessoas do nosso conjunto, podemos dizer que a renda de uma pessoa brasileira está na sua maioria em que faixa (faça faixa de 1.500 reais)?
#  Qual é a sua função densidade de probabilidade?


# Definindo as faixas de renda
faixas = [0, 1500, 3000, 4500, 6000, 7500, 9000, 10500, 12000]
faixa_labels = ['0-1500', '1500-3000', '3000-4500', '4500-6000', '6000-7500', '7500-9000', '9000-10500', '10500-12000']

# Adicionando uma coluna de faixa de renda ao DataFrame
data['faixa_renda'] = pd.cut(data['renda'], bins=faixas, labels=faixa_labels, right=False)

# Contando o número de pessoas em cada faixa
contagem_faixas = data['faixa_renda'].value_counts().sort_index()

# Calculando a densidade de probabilidade
total_pessoas = len(data)
densidade_probabilidade = contagem_faixas / total_pessoas

# Exibindo resultados
print("Número de pessoas em cada faixa de renda:")
print(contagem_faixas)
print("\nDensidade de probabilidade em cada faixa de renda:")
print(densidade_probabilidade)

# 5. Calcule a média e a variância da renda da amostra. Depois faça a distribuição normal, inclua o gráfico.

# Calculando a média e a variância da renda
media_renda = data['renda'].mean()
variancia_renda = data['renda'].var()

print(f'Média da renda: {media_renda:.2f}')
print(f'Variância da renda: {variancia_renda:.2f}')

# Plotando a distribuição normal
# Definindo os parâmetros da distribuição normal
mu = media_renda
sigma = np.sqrt(variancia_renda)

# Gerando valores para a distribuição normal
x = np.linspace(data['renda'].min(), data['renda'].max(), 100)
y = (1 / (sigma * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x - mu) / sigma) ** 2)

# Criando o gráfico
plt.figure(figsize=(8, 5))
sns.histplot(data['renda'], kde=True, stat='density', color='pink', label='Distribuição Observada')
plt.plot(x, y, color='purple', label='Distribuição Normal Ajustada')
plt.title('Distribuição Normal da Renda')
plt.xlabel('Renda')
plt.ylabel('Densidade')
plt.legend()
plt.show()



# 6. Primeiro considere a probabilidade encontrada no nosso conjunto de pessoas com escolaridade de pós-graduação.
# Considerando a amostra de população brasileira com 1 milhão de habitantes, qual a probabilidade de encontrarmos 243 mil pessoas com pós-graduação?

from scipy.stats import binom


# Calculando a probabilidade de ter pós-graduação
total_pessoas = len(data)
pos_count = (data['escolaridade'] == 'Pós-graduação').sum()
probabilidade_pos = pos_count / total_pessoas

print(f'Probabilidade de uma pessoa ter escolaridade Pós-graduação: {probabilidade_pos:.4f}')

# Parâmetros da distribuição binomial
n = 1_000_000  # Tamanho da amostra
k = 243_000    # Número de pessoas com pós-graduação

# Calculando a probabilidade usando a distribuição binomial
probabilidade = binom.pmf(k, n, probabilidade_pos)

print(f'Probabilidade de encontrar 243 mil pessoas com pós-graduação em uma amostra de 1 milhão: {probabilidade:.10f}')

# 7. Somando as densidades nós temos a função dedensidadeacumulada. Considerando a coluna ‘Escolaridade’ faça a função de
#  densidade acumulada discreta para cada nível de escolaridade.

# Calculando a contagem para cada nível de escolaridade
contagem = data['escolaridade'].value_counts().sort_index()

# Calculando a densidade para cada nível de escolaridade
densidade = contagem / len(data)

# Calculando a densidade acumulada
densidade_acumulada = densidade.sort_index().cumsum()

# Exibindo a função de densidade acumulada
print("Função de Densidade Acumulada Discreta por Nível de Escolaridade:")
print(densidade_acumulada)

# 8. Qual a margem de erro amostral da proporção populacional considerando a proporção de pessoas com nível de inglês intermediário?


# Calculando a proporção de pessoas com nível de inglês intermediário
total_pessoas = len(data)
intermediario_count = (data['nível de proficiência em inglês'] == 'Intermediário').sum()
proporcao_intermediario = intermediario_count / total_pessoas

# Calculando a margem de erro
Z = 1.96  # Valor crítico para um intervalo de confiança de 95%
n = total_pessoas  # Tamanho da amostra

margem_erro = Z * np.sqrt((proporcao_intermediario * (1 - proporcao_intermediario)) / n)

print(f'Proporção de pessoas com nível de inglês intermediário: {proporcao_intermediario:.4f}')
print(f'Margem de erro amostral: {margem_erro:.4f}')


#Precisei da ajuda do GPT :
# O valor  𝑍= 1,96 pois é utilizado para calcular a margem de erro com base em um intervalo de confiança de 95%.
# Esse valor vem da distribuição normal padrão e representa a quantidade de desvios padrão (σ) que cobrem 95% da distribuição. Aqui está um pouco mais de detalhes sobre isso:

# 9. Calcula a renda da população. Qual a probabilidade de encontrar 60 pessoas com uma renda mil reais superior à média?

# Calculando a renda média
media_renda = data['renda'].mean()

# Determinando a proporção de pessoas com renda superior à média
total_pessoas = len(data)
renda_superior_media_count = (data['renda'] > media_renda).sum()
proporcao_renda_superior = renda_superior_media_count / total_pessoas

print(f'Renda média: {media_renda:.2f}')
print(f'Proporção de pessoas com renda superior à média: {proporcao_renda_superior:.4f}')

# Parâmetros da distribuição binomial
n = total_pessoas  # Tamanho da amostra
k = 60  # Número de pessoas com renda superior à média

# Calculando a probabilidade usando a distribuição binomial
probabilidade = binom.pmf(k, n, proporcao_renda_superior)

print(f'Probabilidade de encontrar 60 pessoas com renda superior à média: {probabilidade:.10f}')

# 10. Qual a probabilidade de escolhermos alguém do Sudeste que seja homem, com ensino fundamental e comrendamaior que2mil reais por mês?

# Filtrando a amostra de interesse
amostra_interesse = data[
    (data['estado'] == 'SE') &
    (data['sexo'] == 'M') &
    (data['escolaridade'] == 'Fundamental') &
    (data['renda'] > 2000)
]

# Calculando a proporção dessa amostra no total
total_pessoas = len(data)
total_interesse = len(amostra_interesse)

probabilidade = total_interesse / total_pessoas

print(f'Número de pessoas do Sudeste, homens, com ensino fundamental e renda maior que 2 mil reais: {total_interesse}')
print(f'Probabilidade de escolher alguém com essas características: {probabilidade:.4f}')