# -*- coding: utf-8 -*-
"""Desafio Isabela de Souza Silva - Python para Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4EojbfNCkxQKwi4IRVH8qTzjgJ82xah
"""

#Bootcamp Data Analitcs - Turma 07
#Desafio Individual Python para dados
#Squad: Grace Hopper
# Aluna: Isabela de Souza Silva

# Importei as bibliotecas

import pandas as pd
import numpy as np

#Lendo o arquivo que renomeei para saude_do_sono_estilo_vida.csv

data_saude_sono= pd.read_csv("/content/saude_do_sono_estilo_vida.csv")

#Verificando o conteúdo:

data_saude_sono.head(10)

# Verificando as colunas existentes
data_saude_sono.columns

"""1. Ao visualizar a base você percebeu que seria melhor alterar o nome de
algumas colunas. Mude o ‘ID’ para ‘Identificador’, corrija o nome da
coluna que indica a pressão sanguínea, mude a coluna ‘Ocupação’ para
‘Profissão’, a coluna ‘Categoria BMI’ está em parte em inglês, substitua
para ‘Categoria IMC’
"""

data_saude_sono.rename(columns={"Pressão sanguíneaaaa": "Pressão sanguínea", "ID":"Identificador","Ocupação": "Profissão", "Categoria BMI":"Categoria IMC"}, inplace = True)
#Alterei o nome das colunas solictadas
#( inplace=True) para que a mudança seja aplicada diretamente ao DataFrame original

#Vendo se está tudo certo :)

data_saude_sono.columns

data_saude_sono.info()

"""2. Qual é a média, a moda e a mediana de horas de sono para cada uma
das profissões? [‘mean’, np.median, pd.Series.mod]
"""

data_saude_sono.groupby("Profissão")["Duração do sono"].agg(["mean", "median", pd.Series.mode, "sum"])

#Aproveitei para gerar um gráfico para visualizar melhor as diferenças

from matplotlib import pyplot as plt
_df_4["median"].plot(kind="bar", figsize=(15, 4), title="Média de horas de sono/profissão")
plt.gca().spines[["top", "right"]].set_visible(False)

"""3. Das pessoas que atuam com engenharia de software qual a
porcentagem de obesos?
"""

eng_soft_obesos = (data_saude_sono["Categoria IMC"] == "Obesidade") &  (data_saude_sono["Profissão"] =="Eng. de Software")
eng_soft_obesos.sum()

total_eng_soft = (data_saude_sono["Profissão"] =="Eng. de Software")
total_eng_soft.sum()

porcentagem = eng_soft_obesos.sum()/total_eng_soft.sum()*100
f'(A porcentagem de pessoas que atuam com engenharia de software que apresentam obesidade é de {porcentagem}%)'

"""4. De acordo com os dados, advogar ou ser representante de vendas faz
você dormir menos? (Use o método ‘isin’, considere a média)


---


"""

# Filtrei primeiro os dados para Advogados e Representantes
filtro_advogados = data_saude_sono["Profissão"].isin(["Advogado(a)"])
filtro_representantes = data_saude_sono["Profissão"].isin(["Representante de Vendas"])

# Depois, calculei a média de 3 grupos: Advogados, Representates e demais profissões
media_sono_advogados = data_saude_sono[filtro_advogados]["Duração do sono"].mean()
media_sono_advogados

media_sono_representantes = data_saude_sono[filtro_representantes]["Duração do sono"].mean()
media_sono_representantes

media_sono_outras_profissoes = data_saude_sono[~(filtro_advogados|filtro_representantes)]["Duração do sono"].mean()
media_sono_outras_profissoes


if media_sono_outras_profissoes < media_sono_advogados:
  print("Advogados(as) dormem mais que a média de outras profissões. Sorte deles!")
else:
  print(" Os advogados dormem menos que a média de outras profissões. Que triste!")

if media_sono_outras_profissoes < media_sono_representantes:
  print("Representantes comerciais dormem mais que a média de outras profissões. Sorte deles!")
else:
  print("Representantes comerciais dormem menos que a média de outras profissões. Que triste!")

"""5. Entre quem fez enfermagem e quem fez medicina, quem tem menos
horas de sono? (Use o método ‘isin’, considere a média)

"""

data_enfermeiros = data_saude_sono["Profissão"].isin(["Enfermeiro(a)"])
data_enfermeiros.sum()

data_medicos = data_saude_sono["Profissão"].isin(["Médico(a)"])
data_medicos.sum()

# media_sono_enfermeiros = data_saude_sono[data_enfermeiros]["Duração do sono"].mean()
# media_sono

media_sono_enfermeiros = data_saude_sono[data_enfermeiros]["Duração do sono"].mean()
media_sono_enfermeiros

media_sono_medicos = data_saude_sono[data_medicos]["Duração do sono"].mean()
media_sono_medicos

if media_sono_enfermeiros > media_sono_medicos:
  print("Médicos dormem menos mais que enfermeiros!")
else:
  print("Enfermeiros dormem menos que médicos")

"""6. Faça um subconjunto com as colunas Identificador, Gênero, Idade,
Pressão sanguínea e Frequência cardíaca
"""

conjunto = data_saude_sono.loc[:,["Identificador", "Gênero", "Idade", "Pressão sanguínea", "Frequência cardíaca"]]
conjunto

"""7. Descubra qual a profissão menos frequente no conjunto. (Use
value_counts)

"""

data_saude_sono["Profissão"].value_counts()

# Gerente é a profissão com menor frequência = 01

"""8. Quem tem maior pressão sanguínea média, homens ou mulheres?
(Considere a média)
"""

# Foi necessário converter a coluna "Pressão sanguínea" para extrair a pressão "sistólica"(primeiro valor)
# "A pressão arterial é registrada por dois números, os quais são separados por uma barra (120/80 mmHg).
# O primeiro número diz respeito à pressão sistólica, enquanto o segundo se refere à pressão diastólica."
#Dessa forma, escolhi a pressão sistólica para realizar o exercício.
#

# Então criei uma nova coluna retirando a segunda informação da pressão sanguinea:
data_saude_sono["Pressão sistólica"] = data_saude_sono["Pressão sanguínea"].str.split('/').str[0].astype(float)

#Calculei a média da pressão sistólica para cada gênero:
media_pres_sang_mulher = data_saude_sono[data_saude_sono["Gênero"] == "Mulher"]["Pressão sistólica"].mean()
media_pres_sang_homem = data_saude_sono[data_saude_sono["Gênero"] == "Homem"]["Pressão sistólica"].mean()


# Por fim, realizei a comparação dos valorwes:
if media_pres_sang_mulher > media_pres_sang_homem:
    resultado = "Mulheres têm maior pressão sanguínea média do que homens."
else:
    resultado = "Homens têm maior pressão sanguínea média do que mulheres."

resultado

"""9. É predominante entre os participantes dormir 8 horas por dia
(considere usar Moda como medida)?
"""

data_saude_sono["Duração do sono"].mode()

# Não é predominante, pois a moda, valor que mais se repete é 7.2, inferior a 8 horas

"""10. Pessoas com frequências cardíacas acima de 70 dão mais passos que
pessoas com frequência cardíaca menor ou igual a 70? (Use a média)
"""

# Fiz a divisão do grupo 1 = pessoas com frequência cardíaca > 70 e o grupo 2 com pessoas com frequência cardiáca
# abaixo ou igual a 70:

grupo1= data_saude_sono[data_saude_sono["Frequência cardíaca"] > 70]
grupo1.sum()
media_passos_grupo1= grupo1["Passos diários"].mean()

media_passos_grupo1

grupo2= data_saude_sono[data_saude_sono["Frequência cardíaca"] <= 70]
grupo2.sum()
media_passos_grupo2= grupo2["Passos diários"].mean()

media_passos_grupo2

if media_passos_grupo1 > media_passos_grupo2:
  print("Pessoas com frequência cardíaca acima de 70 dão mais passos que pessoas com frequência cardíaca menor ou igual a 70")
else:
  print("Pessoas com frequência cardíaca menor ou igual a 70 dão mais passos que pessoas com frequência cardíaca acima de 70")